#!/usr/bin/env bash
# installs and configures haproxy

sudo apt -y update
sudo apt install -y haproxy

echo "
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 430395-web-01 18.207.141.82:80 check
    server 430395-web-02 52.90.22.133:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
